### ISSUE TITLE
Issue starting the HTTPS and WinRM servers 

### ISSUE THREAD

**Issue by ThePenetrator** [lgandx/Responder#184] opened 2022-01-06 18:48 UTC
Some missing dummy certificate files in certs are missing which prevents the HTTPS and WinRM services from starting. 

README.md states that there should be some dummy certs in there to allow the tool to start, but they are not present. 

Moreover, running the included script breaks when you run it within the certs directory because of the bad paths in the openssl commands. 

Regenerating the certs manually with the correct path fixes the issue.

![image](https://user-images.githubusercontent.com/16773244/148434821-58c95b5a-5996-427c-9ea0-35f85361f736.png)

**Comment by lgandx** [comment] 2022-01-06 18:59
Hi,

That can happen after a git pull for the older version.
Best way to fix this issue, is to delete the Responder.db file.

**Comment by ThePenetrator** [comment] 2022-01-06 19:01
This was a fresh git pull from the repo.

![image](https://user-images.githubusercontent.com/16773244/148436717-64f5b4de-aaae-47f8-9fce-750e17e15959.png)

**Comment by lgandx** [comment] 2022-01-14 14:14
I can't reproduce this issue in my lab, do you have any additional information on the environment or was this issue resolved on your end ?

**Comment by antifob** [comment] 2022-05-04 18:37
@ThePenetrator Creepy name aside, Responder assumes that the script is running from the project's root directory. If you're not and this fixes your issue, can you close this ticket please?

**Comment by lgandx** [comment] 2022-08-05 21:28
closing this issue as resolved.

**Closed by lgandx** 2022-08-05 21:28 UTC
