### ISSUE TITLE
Database Locked

### ISSUE THREAD

**Issue by ablito19** [lgandx/Responder#234] opened 2023-03-16 16:04 UTC
When i run Responder with Poisoned Options, I get error like :

sqlite3.operationalerror database is locked responder/poisoners/MDNS.py

**Comment by lgandx** [comment] 2023-03-16 18:08
Hi,

Try deleting Responder.db and start responder.

Cheers,

**Comment by lgandx** [comment] 2023-05-22 22:50
Can't reproduce, closing for now.

**Closed by lgandx** 2023-05-22 22:50 UTC
